[install]
is_configured = false

[ui]
is_visible = 1
label = Mission Control Inventory

[launcher]
author = Adam Liquorish
version = 1.0.1
description = Lookup-driven Splunk Cloud app for querying local Mission Control / SOAR inventory endpoints through Splunkd.

[package]
id = TA-missioncontrol-inventory
check_for_updates = true

[id]
name = TA-missioncontrol-inventory
version = 1.0.1
