[mcquery]
filename = mcquery.py
chunked = true
local = true
generating = true
python.version = python3
python.required = 3.13

[mcpost]
filename = mcpost.py
chunked = true
local = true
generating = true
python.version = python3
python.required = 3.13
