[loggers]
keys=root

[handlers]
keys=mcquery_file

[formatters]
keys=mcquery_format

[logger_root]
level=INFO
handlers=mcquery_file

[handler_mcquery_file]
class=logging.handlers.RotatingFileHandler
level=INFO
formatter=mcquery_format
args=('%(SPLUNK_HOME)s/var/log/splunk/mcquery.log', 'a', 10485760, 3)

[formatter_mcquery_format]
format=%(asctime)s, level=%(levelname)s, pid=%(process)s, logger=%(name)s, %(message)s
