[Mission Control - Current Inventory Lookup]
disabled = 1
action.email = 0
cron_schedule = 0 2 * * *
enableSched = 0
search = | mcquery all=true include_raw=false | outputlookup missioncontrol_inventory_current.csv

[Mission Control - Daily Inventory Snapshot]
disabled = 1
action.email = 0
cron_schedule = 15 2 * * *
enableSched = 0
search = | mcquery all=true include_raw=true | collect index=summary sourcetype=missioncontrol:inventory marker="source=mcquery"
